name: Jira Add Comment
description: Add a comment to an issue
branding:
  icon: 'align-left'
  color: 'blue'
inputs:
  issues_keys:
    description: issues keys as string separated by ", " e.g. "VTX-1, VTX-2"
    required: true
  comment:
    description: Comment
    required: true
runs:
  using: 'node12'
  main: './dist/index.js'
